package IHM;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;

import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

import Moteur.CreateBaseDeRegle;
import Moteur.Fait;
import Moteur.Moteur;
import Moteur.Regle;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



/**
 *
 * @author Thierry
 */
public class Mainframe extends javax.swing.JFrame {
	/**
	 * Creates new form Mainframe
	 */

	CreateBaseDeRegle rb;
	ArrayList<Regle>baseDeRegle;
	ArrayList<Fait>baseDeFait;
	Moteur m;
	Fait but;

	public Mainframe() {
		setTitle("Expert system application");
		initComponents();
		CustomOutputStream taos = new CustomOutputStream( jTextArea1, 1500 );
		PrintStream ps = new PrintStream( taos );
		System.setOut( ps );
		System.setErr( ps );

		rb = new CreateBaseDeRegle("Rules");
		rb.generateRuleBased();

		baseDeRegle=rb.getRulesBase();

		baseDeFait= new ArrayList<Fait>();

		baseDeFait.add(new Fait("auteur","=","Boris_Vian"));

		baseDeFait.add(new Fait("theme","=","vengeance"));

		but = new Fait("livre","=","J_irai_cracher_sur_vos_tombes");


		m = new Moteur(baseDeFait,baseDeRegle);

		System.out.println("Starting Expert system app :\n");

		printRulesAndFact();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jTextField3 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		operatorCombo = new javax.swing.JComboBox<>();
		jLabel9 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		operatorCombo1 = new javax.swing.JComboBox<>();
		jButton5 = new javax.swing.JButton();
		jCheckBox2 = new javax.swing.JCheckBox();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		jCheckBox1.setText("jCheckBox1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel3.setText("Rules base :");

		jLabel4.setText("Facts base :");

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel7.setText("Fact");

		jLabel8.setText("Operator");

		operatorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">", ">=", "<=", "!=", "=" }));
		operatorCombo.setSelectedItem("=");
		operatorCombo.setToolTipText("");

		jLabel9.setText("Value");

		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		jButton4.setText("Add fact");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 325, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(67, 67, 67)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel7)
												.addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
												.addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
												.addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(operatorCombo, 0, 44, Short.MAX_VALUE)
												.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(96, Short.MAX_VALUE)))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 278, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jLabel8)
								.addGap(2, 2, 2)
								.addComponent(operatorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19)
								.addComponent(jLabel9)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)
								.addComponent(jButton4)
								.addContainerGap(35, Short.MAX_VALUE)))
				);

		jLabel2.setText("Add a fact to facts base :");

		jLabel5.setText("Select motor :");

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel11.setText("Chaining mode :");

		operatorCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Backward chaining", "Forward chaining" }));
		operatorCombo1.setSelectedItem("=");
		operatorCombo1.setToolTipText("");
		operatorCombo1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				operatorCombo1ActionPerformed(evt);
			}
		});

		jButton5.setText("Start");
		jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton5MouseClicked(evt);
			}
		});
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 325, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(67, 67, 67)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
										.addComponent(jLabel11)
										.addComponent(operatorCombo1, 0, 192, Short.MAX_VALUE))
								.addContainerGap(66, Short.MAX_VALUE)))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 278, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(81, 81, 81)
								.addComponent(jLabel11)
								.addGap(2, 2, 2)
								.addComponent(operatorCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(54, 54, 54)
								.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(35, Short.MAX_VALUE)))
				);

		jCheckBox2.setText("Logs");
		jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jCheckBox2MouseClicked(evt);
			}
		});
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
		jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jMenu1.setText("Select rules base file");
		jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenu1MouseClicked(evt);
			}
		});
		jMenu1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenu1ActionPerformed(evt);
			}
		});
		jMenuBar1.add(jMenu1);

		jMenu3.setText("Console mode");
		jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jMenu3MouseClicked(evt);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jMenuBar1.add(jMenu3);

		jMenu2.setText("help");
		jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenu2MouseClicked(evt);
			}
		});
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane2.setViewportView(jTextArea2);

		jTextArea2.setEditable(false);
		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea3 = new javax.swing.JTextArea();
		jScrollPane3.setViewportView(jTextArea3);

		jTextArea3.setEditable(false);
		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);

		button = new JButton("Reset facts base");
		button.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				baseDeFait=new ArrayList<Fait>();
				printRulesAndFact();
			}
		});
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		panel = new JPanel();
		panel.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));

		lblFactToProve = new JLabel("Fact to prove :");
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(10)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(jLabel2)
							.addGap(224)
							.addComponent(lblFactToProve, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
							.addGap(207)
							.addComponent(jLabel5)
							.addGap(268)
							.addComponent(jLabel3))
						.addGroup(groupLayout.createSequentialGroup()
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(groupLayout.createSequentialGroup()
									.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(panel, GroupLayout.PREFERRED_SIZE, 271, GroupLayout.PREFERRED_SIZE)
									.addGap(24)
									.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addComponent(jCheckBox2))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 561, GroupLayout.PREFERRED_SIZE)
								.addGroup(groupLayout.createSequentialGroup()
									.addGap(4)
									.addComponent(jLabel4)
									.addGap(10)
									.addComponent(button))))
						.addGroup(groupLayout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 971, GroupLayout.PREFERRED_SIZE)
							.addGap(10)
							.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 561, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(16)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel2)
						.addComponent(jLabel5)
						.addComponent(jLabel3)
						.addComponent(lblFactToProve))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE)
							.addGap(6)
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addGroup(groupLayout.createSequentialGroup()
									.addGap(4)
									.addComponent(jLabel4))
								.addComponent(button)))
						.addGroup(groupLayout.createSequentialGroup()
							.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(jPanel2, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
								.addComponent(jPanel1, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
								.addComponent(panel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jCheckBox2)))
					.addGap(9)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)))
		);

		label = new JLabel();
		label.setText("Fact");

		txtLivre = new JTextField();
		txtLivre.setText("livre");

		label_1 = new JLabel();
		label_1.setText("Operator");

		comboBox = new JComboBox<String>();
		comboBox.addItem("=");
		comboBox.addItem("<");
		comboBox.addItem(">");
		comboBox.addItem("<=");
		comboBox.addItem(">=");
		comboBox.addItem("!=");

		//comboBox.setToolTipText("test");

		label_2 = new JLabel();
		label_2.setText("Value");

		txtJiraicrachersurvostombes = new JTextField();
		txtJiraicrachersurvostombes.setText("J_irai_cracher_sur_vos_tombes");
		GroupLayout gl_panel = new GroupLayout(panel);
		gl_panel.setHorizontalGroup(
				gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
						.addGap(50)
						.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
								.addComponent(txtJiraicrachersurvostombes, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
								.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtLivre, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
								.addComponent(label, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
						.addGap(59))
				);
		gl_panel.setVerticalGroup(
				gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
						.addContainerGap()
						.addComponent(label)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(txtLivre, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
						.addGap(18)
						.addComponent(label_1)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
						.addGap(18)
						.addComponent(label_2)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(txtJiraicrachersurvostombes, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(83, Short.MAX_VALUE))
				);
		panel.setLayout(gl_panel);
		getContentPane().setLayout(groupLayout);

		pack();
	}// </editor-fold>                        

	private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
		// TODO add your handling code here:
	}                                      

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
	}                                           

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	}                                        

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	}                                        

	private void operatorCombo1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
		// TODO add your handling code here:
	}                                              

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
	}                                          

	private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) throws InterruptedException {        

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				MenuConsole.menuConsole();
			}
		});

	}                                   

	private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {                                    
		// TODO add your handling code here:
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
		int result = fileChooser.showOpenDialog(getParent());
		if (result == JFileChooser.APPROVE_OPTION) {
			File selectedFile = fileChooser.getSelectedFile();
			System.out.println("Opening : "+selectedFile);
			rb = new CreateBaseDeRegle(selectedFile.getName());
			rb.generateRuleBased();
			baseDeRegle=rb.getRulesBase();
			m = new Moteur(baseDeFait,baseDeRegle);
			System.out.println("Rule base updated !");
			System.out.println(baseDeRegle);
		}
	}                                   

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:
		if(!jTextField3.getText().isEmpty()&&!jTextField4.getText().isEmpty()) {
			System.out.println("Adding fact : " +jTextField3.getText() +" "+operatorCombo.getSelectedItem().toString() +" "+jTextField4.getText());
			baseDeFait.add(new Fait(jTextField3.getText(),operatorCombo.getSelectedItem().toString(),jTextField4.getText()));
			printRulesAndFact();
			m=new Moteur(baseDeFait,baseDeRegle);
		}else {
			System.out.println("Fact is missing value.");
		}
	}                                     


	private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {                                      
		// TODO add your handling code here:*
		if(!txtLivre.getText().isEmpty()&&!txtJiraicrachersurvostombes.getText().isEmpty()) {
			System.out.println("Starting motor.");
			System.out.println("With fact : "+new Fait(txtLivre.getText(),comboBox.getSelectedItem().toString(),txtJiraicrachersurvostombes.getText()));

			if(operatorCombo1.getSelectedItem().toString().equals("Backward chaining")) {
				System.out.println("Motor selected : Backward"+jCheckBox1.isSelected());
				m.chainageArrière(new Fait(txtLivre.getText(),comboBox.getSelectedItem().toString(),txtJiraicrachersurvostombes.getText()), jCheckBox2.isSelected());
			}else {
				System.out.println("Motor selected : Forward");
				m.chainageAvant(new Fait(txtLivre.getText(),comboBox.getSelectedItem().toString(),txtJiraicrachersurvostombes.getText()), jCheckBox2.isSelected());
			}
		}else {
			System.out.println("No fact to prove.");
		}
	}                                     

	private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {                                        
		// TODO add your handling code here:
	}                                       

	private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {                                    
		// TODO add your handling code here:
	}                                   

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Mainframe().setVisible(true);
			}
		});
	}

	public void printRulesAndFact() {
		jTextArea2.setText("");
		jTextArea3.setText("");
		int cpt=0;
		for (Regle r : baseDeRegle) {
			jTextArea2.setText(jTextArea2.getText()+"\n\nRule n° "+ ++cpt +"\n============"+r.toString());
		}
		cpt=0;
		for (Fait f : baseDeFait) {
			jTextArea3.setText(jTextArea3.getText()+"\n\nFact n° "+ ++cpt +"\n============\n"+f.toString());
		}
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JComboBox<String> operatorCombo;
	private javax.swing.JComboBox<String> operatorCombo1;
	private JButton button;
	private JPanel panel;
	private JLabel lblFactToProve;
	private JLabel label;
	private JTextField txtLivre;
	private JLabel label_1;
	private JComboBox<String> comboBox;
	private JLabel label_2;
	private JTextField txtJiraicrachersurvostombes;
	// End of variables declaration                   
}
